name: flutter_security
description: A flutter package that aim to take care of your mobile app security side.
version: 0.1.4
homepage: https://github.com/marcotrumpet/flutter_security

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^4.1.3
  json_annotation: ^4.0.1
  freezed_annotation: ^0.14.2
  encrypt: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.0.6
  freezed: ^0.14.2

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_security
        pluginClass: FlutterSecurityPlugin
      ios:
        pluginClass: FlutterSecurityPlugin